# Generated by Django 4.2.6 on 2023-10-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salts',
            name='sha256sum',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
